# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parallel-SubFork
version:      0.01
version_from: lib/Parallel/SubFork.pm
installdirs:  site
requires:
    Carp:                          0
    Class::Accessor::Fast:         0
    POSIX:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
