# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parallel-SubFork
version:      0.05
version_from: lib/Parallel/SubFork.pm
installdirs:  site
requires:
    Carp:                          0
    Class::Accessor::Fast:         0
    FindBin:                       0
    IPC::Semaphore:                0
    IPC::SysV:                     0
    POSIX:                         0
    Test::More:                    0
    Test::Pod:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
